version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8082:8082