# Generated by Django 5.0 on 2023-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
